@startuml Contoh Kasus

skinparam Shadowing true
skinparam BackgroundColor #f5f6f8
skinparam LegendBackgroundColor #f5f6f8

start

#white:Masukkan kode baju (1/2);

if (kode baju = 1) then (true)
#LightBlue:merk = H&R;

#white:Masukkan ukuran baju (S/M);

if (ukuran baju = S) then (true)
  #LightBlue:harga = 45000;
(false) elseif (ukuran baju = M) then (true)
  #LightBlue:harga = 60000;
else (false)
  #LightBlue:harga = 0;
endif

#LightCyan:cout << Merek baju: merk;
#LightCyan:cout << Harga baju: harga;

(false) elseif (kode baju = 2) then (true)
#LightBlue:merk = Adidas;

#white:Masukkan ukuran baju (S/M);

if (ukuran baju = S) then (true)
  #LightBlue:harga = 65000;
(false) elseif (ukuran baju = M) then (true)
  #LightBlue:harga = 75000;
else (false)
  #LightBlue:harga = 0;
endif

#LightCyan:cout << Merek baju: merk;
#LightCyan:cout << Harga baju: harga;

else (false)
#LightCyan:cout << Kode Salah;
endif
stop

header
  Pertemuan 3

endheader
title Contoh Kasus
caption copyright@esaunggul.ac.id
legend right
CTI121 - Desain dan Analisa Algoritma
endlegend

@enduml